[workspace]
resolver = "3"
members = ["Io-lab/nonblock-io", "async-lab/tokio-lab",
  "cli-lab/clap-lab", "enum/strum-lab", "error-lab/this_error_demo", "error-lab/unified_error", "high-performance-lab/false-sharing","mvp", "process-lab/process", "process-lab/self-pipe-trick", "readline-lab/rustyline-lab", "std/fs/file", "std/io", "std/iter/iter-menthod", "std/mem/maybeuninit", "std/thread", "template-lab/tera-lab", "test-lab/basic-test", "trie-lab/radix-trie-lab", "unsafecell-lab/unsafecell-lab", "volatile-lab",
]
