[package]
name = "mvp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
tera = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
chrono = "0.4"

[build-dependencies]
glob = "0.3"
