[package]
name = "mvp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
tera = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
chrono = "0.4"
strum = { version = "0.27", features = ["derive"] }
enum_dispatch = "0.3.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
[build-dependencies]
glob = "0.3"

[dev-dependencies]
tempfile = "3.6"  # 指定最新稳定版本即可
